### ISSUE TITLE
knife4j 扫不到接口

### ISSUE THREAD

**Issue by zenmo972** [Sonder-MX/sky-take-out#3]
因为新版本不需要静态链接，改application.yml  文件的配置。

```yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:   ## 此处改为需要扫描的包路径


```

你用的还是 com.github.xiaoymin.boot3 肯定扫不出来啊
